- name: Install Apache2 Web Server
  hosts: webserver
  become: yes
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Install Apache2 package
      apt:
        name: apache2
        state: present
      
    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
